//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ra2CsfToolsGUI.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ra2CsfToolsGUI.LocalizationResources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved successfully.
        /// </summary>
        public static string Cs_Txt_ChangesSaved {
            get {
                return ResourceManager.GetString("Cs_Txt_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Westwood RA2 string table files (*.csf)|*.csf.
        /// </summary>
        public static string Cs_Txt_CsfFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_CsfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one file is allowed for drag &amp; drop..
        /// </summary>
        public static string Cs_Txt_DragAndDropSingleFile {
            get {
                return ResourceManager.GetString("Cs_Txt_DragAndDropSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - {0}.
        /// </summary>
        public static string Cs_Txt_Error {
            get {
                return ResourceManager.GetString("Cs_Txt_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;FileSystemWatcher.Changed&apos; triggered. Source: {0}.
        /// </summary>
        public static string Cs_Txt_EventTriggered {
            get {
                return ResourceManager.GetString("Cs_Txt_EventTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read map file {0}: {1}.
        /// </summary>
        public static string Cs_Txt_FailedToReadMapFile {
            get {
                return ResourceManager.GetString("Cs_Txt_FailedToReadMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This string table file contains {0} labels, with language {1}..
        /// </summary>
        public static string Cs_Txt_FileContainsLabelsAndLanguage {
            get {
                return ResourceManager.GetString("Cs_Txt_FileContainsLabelsAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String table files (*.csf;*.ini;*.yaml;*.json)|*.csf;*.ini;*.yaml;*.json|Westwood RA2 string table files (*.csf)|*.csf|SadPencil.Ra2CsfFile.Ini files (*.ini)|*.ini|SadPencil.Ra2CsfFile.Yaml files (*.yaml)|*.yaml|JSON files (*.json)|*.json.
        /// </summary>
        public static string Cs_Txt_FileFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully. This string table file contains {0} labels, with language {1}..
        /// </summary>
        public static string Cs_Txt_FileLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Cs_Txt_FileLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully. Would you like to open the file in File Explorer?.
        /// </summary>
        public static string Cs_Txt_FileSavedSuccessAndOpenFolder {
            get {
                return ResourceManager.GetString("Cs_Txt_FileSavedSuccessAndOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not exist!.
        /// </summary>
        public static string Cs_Txt_FolderDoesNotExist {
            get {
                return ResourceManager.GetString("Cs_Txt_FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Cs_Txt_Information {
            get {
                return ResourceManager.GetString("Cs_Txt_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SadPencil.Ra2CsfFile.Ini files (*.ini)|*.ini.
        /// </summary>
        public static string Cs_Txt_IniFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_IniFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters found in label name \&quot;{0}\&quot;..
        /// </summary>
        public static string Cs_Txt_InvalidCharactersInLabelName {
            get {
                return ResourceManager.GetString("Cs_Txt_InvalidCharactersInLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid watch config line: {0}.
        /// </summary>
        public static string Cs_Txt_InvalidWatchConfig {
            get {
                return ResourceManager.GetString("Cs_Txt_InvalidWatchConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json.
        /// </summary>
        public static string Cs_Txt_JsonFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_JsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load a string table file first..
        /// </summary>
        public static string Cs_Txt_LoadFileFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_LoadFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load the string table files first..
        /// </summary>
        public static string Cs_Txt_LoadFilesFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_LoadFilesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} labels are missing..
        /// </summary>
        public static string Cs_Txt_MissingLabelsResult {
            get {
                return ResourceManager.GetString("Cs_Txt_MissingLabelsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Cs_Txt_Result {
            get {
                return ResourceManager.GetString("Cs_Txt_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the map folder first..
        /// </summary>
        public static string Cs_Txt_SelectMapFolderFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_SelectMapFolderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Cs_Txt_Success {
            get {
                return ResourceManager.GetString("Cs_Txt_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected file extension. Only .csf, .ini, .yaml, and .json files are accepted..
        /// </summary>
        public static string Cs_Txt_UnexpectedFileExtension {
            get {
                return ResourceManager.GetString("Cs_Txt_UnexpectedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch mode is configured. Do you want to start it?.
        /// </summary>
        public static string Cs_Txt_WatchModeConfirm {
            get {
                return ResourceManager.GetString("Cs_Txt_WatchModeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SadPencil.Ra2CsfFile.Yaml files (*.yaml)|*.yaml.
        /// </summary>
        public static string Cs_Txt_YamlFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_YamlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a string table file (.csf/.ini/.yaml/.json) ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton1_Advanced {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton1_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton1_Basic {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton1_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as a .csf file ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as a .yaml file ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as a .json file ....
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Converter.
        /// </summary>
        public static string Xaml_Txt_FormatConverterTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string table of Red Alert 2 is presented as a .csf file, which is not friendly for editing as most csf editors were created decades ago. This tool allows users to convert the string table from a .csf file to an .ini file and back to a .csf file that is recognized by the game..
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: the text encoding of the .ini file must be UTF-8 (without BOM)..
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the string table file is shown below for preview. To modify it, save it as an .ini file..
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Mode.
        /// </summary>
        public static string Xaml_Txt_HomeTabAdvancedMode {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Xaml_Txt_HomeTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool helps users process string table files (.csf) that are recognized by Red Alert 2 and Yuri&apos;s Revenge. It allows you to:.
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the .csf file using your favorite text editor by converting it to an .ini file and then back to a .csf file..
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to keep the .csf file. You can just store the .ini file in your Git repository, as it contains everything needed to generate a .csf file..
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More features available in &quot;Advanced Mode&quot;....
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile the translated file with the upstream file, so you can complete the translation without having to compare two files side by side..
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the translation updates between old and new versions of your old translation, so you can effectively update it..
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock6 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, simply drag &amp; drop a .csf/.ini file here..
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock7 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder containing map files (.map/.ypr) ....
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file ....
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Check.
        /// </summary>
        public static string Xaml_Txt_LabelCheckTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether there are missing CSF labels in your map files..
        /// </summary>
        public static string Xaml_Txt_LabelCheckTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: in the generated .ini file, all values of missing labels are replaced with the following text:.
        /// </summary>
        public static string Xaml_Txt_LabelCheckTextboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTextboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the current string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as a .csf file ....
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file ....
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Override.
        /// </summary>
        public static string Xaml_Txt_LabelOverrideTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool can now support label names containing capital letters. Select an upstream string table file, and your current string table file. The tool will compare each label (ignoring case) and prefer the label from upstream..
        /// </summary>
        public static string Xaml_Txt_LabelOverrideTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows-1252 workaround when loading the .csf file..
        /// </summary>
        public static string Xaml_Txt_SettingsCheckbox1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsCheckbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows-1252 workaround when writing the .csf file..
        /// </summary>
        public static string Xaml_Txt_SettingsCheckbox2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsCheckbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding 1252 Workaround Options.
        /// </summary>
        public static string Xaml_Txt_SettingsGroupboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsGroupboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Xaml_Txt_SettingsTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For code points 128-159 (0x80-0x9F), the original game.fnt file of RA2 mistakenly treats these characters as Windows-1252, instead of Unicode (ISO-8859-1). In some mods and some editors, those characters may be saved as Windows-1252 encoding, which is incorrect. However, users may still need to process these files. You can decide whether to treat 128-159 as Windows-1252 or as Unicode. Checking the two boxes below means the former, which is compatible with some mods and some editors. Un-checking the two boxe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xaml_Txt_SettingsTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationNewButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file for translation ....
        /// </summary>
        public static string Xaml_Txt_TranslationNewButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Helper - New.
        /// </summary>
        public static string Xaml_Txt_TranslationNewTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an upstream string table file, and save an .ini file that is friendly for translation. The .ini file can be converted back to .csf file in the &quot;Format Converter&quot; tab..
        /// </summary>
        public static string Xaml_Txt_TranslationNewTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: in the generated .ini file, all values that needs translation are replaced with the following text:.
        /// </summary>
        public static string Xaml_Txt_TranslationNewTextboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTextboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a translated string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file for comparison ....
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Helper - Override.
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an upstream string table file and a translated string label file, and save an .ini file that once a label is shown in the translated file, the value is selected. Otherwise, the label shown in the upstream file is selected. The .ini file can be converted back to .csf file in the &quot;Format Converter&quot; tab..
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a translated string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file for comparison ....
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Helper - Tile.
        /// </summary>
        public static string Xaml_Txt_TranslationTileTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an upstream string table file and a translated string label file, and save an .ini file that is convenient for comparing and checking. The .ini file can be converted back to .csf file in the &quot;Format Converter&quot; tab..
        /// </summary>
        public static string Xaml_Txt_TranslationTileTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an old-version upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a new-version upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an old-version translated string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file for updating the translation ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an old-version upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a new-version upstream string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an old-version translated string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a new-version translated string table file (.csf/.ini) ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an .ini file for updating the translation ....
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Helper - Update Check.
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an old-version upstream string table file, a new-version upstream string table file, an old-version translated string label file, and a new-version translated string label file, and save an .ini file that is checked for whether some labels remain the old version. The .ini file can be converted back to .csf file in the &quot;Format Converter&quot; tab..
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Helper - Update.
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an old-version upstream string table file, a new-version upstream string table file and an old-version translated string label file, and save an .ini file that is convenient for updating the translation. The .ini file can be converted back to .csf file in the &quot;Format Converter&quot; tab..
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Apply.
        /// </summary>
        public static string Xaml_Txt_WatchModeButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Mode.
        /// </summary>
        public static string Xaml_Txt_WatchModeTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the text box below, input the pairs of .ini files to monitor and the corresponding .csf files to generate. Separate each pair with a comma. You can enter multiple pairs by putting each pair on a new line. Once the program starts, it will monitor the .ini files. Whenever an ini file changes, the program will automatically generate the corresponding csf file..
        /// </summary>
        public static string Xaml_Txt_WatchModeTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:\path\to\stringtables\ra2.ini, D:\path\to\game\ra2.csf.
        /// </summary>
        public static string Xaml_Txt_WatchModeTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTextBlock2", resourceCulture);
            }
        }
    }
}
