//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ra2CsfToolsGUI.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ra2CsfToolsGUI.LocalizationResources.TextResources - Copy", typeof(TextResources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Mode.
        /// </summary>
        public static string HomeTabAdvancedMode {
            get {
                return ResourceManager.GetString("HomeTabAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTabHeader {
            get {
                return ResourceManager.GetString("HomeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool helps users process string table files (.csf) that are recognized by Red Alert 2 and Yuri&apos;s Revenge. It allows you to:.
        /// </summary>
        public static string HomeTabTextBlock1 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the .csf file using your favorite text editor by converting it to an .ini file and then back to a .csf file..
        /// </summary>
        public static string HomeTabTextBlock2 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to keep the .csf file. You can just store the .ini file in your Git repository, as it contains everything needed to generate a .csf file..
        /// </summary>
        public static string HomeTabTextBlock3 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More features available in &quot;Advanced Mode&quot;....
        /// </summary>
        public static string HomeTabTextBlock4 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile the translated file with the upstream file, so you can complete the translation without having to compare two files side by side..
        /// </summary>
        public static string HomeTabTextBlock5 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the translation updates between old and new versions of your old translation, so you can effectively update it..
        /// </summary>
        public static string HomeTabTextBlock6 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, simply drag &amp; drop a .csf/.ini file here..
        /// </summary>
        public static string HomeTabTextBlock7 {
            get {
                return ResourceManager.GetString("HomeTabTextBlock7", resourceCulture);
            }
        }
    }
}
