//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ra2CsfToolsGUI.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ra2CsfToolsGUI.LocalizationResources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Your changes have been saved successfully. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_ChangesSaved {
            get {
                return ResourceManager.GetString("Cs_Txt_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All content has been copied to the clipboard. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_CopyAllSuccess {
            get {
                return ResourceManager.GetString("Cs_Txt_CopyAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Westwood RA2 string table files (*.csf)|*.csf 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_CsfFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_CsfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one file can be dropped at a time. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_DragAndDropSingleFile {
            get {
                return ResourceManager.GetString("Cs_Txt_DragAndDropSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_Error {
            get {
                return ResourceManager.GetString("Cs_Txt_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read map file {0}: {1} 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FailedToReadMapFile {
            get {
                return ResourceManager.GetString("Cs_Txt_FailedToReadMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This string table file contains {0} labels, with language {1}. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FileContainsLabelsAndLanguage {
            get {
                return ResourceManager.GetString("Cs_Txt_FileContainsLabelsAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String table files (*.csf;*.ini;*.yaml;*.json)|*.csf;*.ini;*.yaml;*.json|Westwood RA2 string table files (*.csf)|*.csf|SadPencil.Ra2CsfFile.Ini files (*.ini)|*.ini|SadPencil.Ra2CsfFile.Yaml files (*.yaml)|*.yaml|JSON files (*.json)|*.json 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FileFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File loaded successfully. This string table contains {0} labels, with language {1}. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FileLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Cs_Txt_FileLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File saved successfully. Would you like to open it in File Explorer? 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FileSavedSuccessAndOpenFolder {
            get {
                return ResourceManager.GetString("Cs_Txt_FileSavedSuccessAndOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder {0} does not exist! 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_FolderDoesNotExist {
            get {
                return ResourceManager.GetString("Cs_Txt_FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_Information {
            get {
                return ResourceManager.GetString("Cs_Txt_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SadPencil.Ra2CsfFile.Ini files (*.ini)|*.ini 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_IniFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_IniFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid characters found in label name &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_InvalidCharactersInLabelName {
            get {
                return ResourceManager.GetString("Cs_Txt_InvalidCharactersInLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid watch config line: {0} 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_InvalidWatchConfig {
            get {
                return ResourceManager.GetString("Cs_Txt_InvalidWatchConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON files (*.json)|*.json 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_JsonFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_JsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something you should be aware of. There is a label named &quot;0&quot;. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_LabelCheckLabel0Warning {
            get {
                return ResourceManager.GetString("Cs_Txt_LabelCheckLabel0Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked {0} map files. Found a total of {1} unique labels, with {2} of them missing. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_LabelCheckResult {
            get {
                return ResourceManager.GetString("Cs_Txt_LabelCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load a string table file first. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_LoadFileFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_LoadFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load the string table files first. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_LoadFilesFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_LoadFilesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_Result {
            get {
                return ResourceManager.GetString("Cs_Txt_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the map folder first. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_SelectMapFolderFirst {
            get {
                return ResourceManager.GetString("Cs_Txt_SelectMapFolderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_Success {
            get {
                return ResourceManager.GetString("Cs_Txt_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected file extension. Only .csf, .ini, .yaml, and .json files are accepted. 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_UnexpectedFileExtension {
            get {
                return ResourceManager.GetString("Cs_Txt_UnexpectedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watch mode is configured. Do you want to start it? 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_WatchModeConfirm {
            get {
                return ResourceManager.GetString("Cs_Txt_WatchModeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SadPencil.Ra2CsfFile.Yaml files (*.yaml)|*.yaml 的本地化字符串。
        /// </summary>
        public static string Cs_Txt_YamlFilter {
            get {
                return ResourceManager.GetString("Cs_Txt_YamlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton1_Advanced {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton1_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a string table file (.csf/.ini) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton1_Basic {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton1_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as a .csf file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as a .yaml file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as a .json file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButton5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterButtonCopyAll {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterButtonCopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Converter 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red Alert 2 string tables are stored in .csf files, which can be a hassle to edit with tools that are two decades old. This tool lets you convert a string table from a .csf file to a more editable .ini file and then convert it back to a game-recognized .csf file. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: The .ini file must be encoded as UTF-8 (without BOM). 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string table content is shown below for preview. To modify it, you must save it as an .ini file first. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_FormatConverterTextBlock3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_FormatConverterTextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Mode 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabAdvancedMode {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabAdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tool helps you process string table files (.csf) for Red Alert 2 and Yuri&apos;s Revenge, allowing you to: 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert .csf files to .ini format for easy editing in your preferred text editor, then convert them back to .csf. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t need to save the .csf file. The .ini file contains all the necessary data to generate a .csf file, making it ideal for storage in a Git repository. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More features are available in &quot;Advanced Mode&quot;... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare a translated file with the upstream file side-by-side, which simplifies the translation process. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight updated translations between old and new versions, making it easier to see and apply changes. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock6 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To get started, simply drag and drop a .csf or .ini file here. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_HomeTabTextBlock7 {
            get {
                return ResourceManager.GetString("Xaml_Txt_HomeTabTextBlock7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load one or more string table files (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the folder containing map files (.map/.mpr/.yrm) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label Check 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks for missing .csf labels in your map files. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: In the generated .ini file, the values for all missing labels will be replaced with the following text: 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelCheckTextboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelCheckTextboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load the current string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as a .csf file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label Override 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tool now supports label names with capital letters. Select an upstream file and your current file. The tool will compare each label, ignoring case, and use the label from the original file as the preferred one. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_LabelOverrideTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_LabelOverrideTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load file A (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load file B (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save A union B ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save A intersection B ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save A minus B ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save B minus A as .csf ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsButton6 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsButton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: In the generated .ini file, labels that exist in both A and B but have different values will use the following placeholder text: 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsDifferentValuePlaceholderHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsDifferentValuePlaceholderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Operations 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform set operations on string table files by comparing keys. Load two files A and B, then generate union, intersection, or differences. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SetOperationsTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SetOperationsTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Windows-1252 workaround when loading the .csf file. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsEncoding1252Checkbox1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsEncoding1252Checkbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Windows-1252 workaround when writing the .csf file. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsEncoding1252Checkbox2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsEncoding1252Checkbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encoding 1252 Workaround Options 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsEncoding1252GroupboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsEncoding1252GroupboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original RA2 `game.fnt` file incorrectly treats code points 128-159 (0x80-0x9F) as Windows-1252 instead of Unicode (ISO-8859-1). While this is incorrect, some mods and editors save these characters with Windows-1252 encoding. This tool allows you to decide whether to treat these code points as Windows-1252 or Unicode. Checking the two boxes below enables the Windows-1252 workaround for compatibility with certain mods and editors. Un-checking them uses the correct Unicode interpretation. The original `ga [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsEncoding1252TextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsEncoding1252TextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order by key 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsLabelOrderCheckbox1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsLabelOrderCheckbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label orders 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsLabelOrderGroupboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsLabelOrderGroupboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_SettingsTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationNewButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file for translation ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationNewButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Helper - New 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationNewTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an upstream file and save it as a translation-friendly .ini file. You can convert this .ini file back to a .csf file using the &quot;Format Converter&quot; tab. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationNewTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: In the generated .ini file, all values that require translation will be replaced with the following text: 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationNewTextboxHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationNewTextboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a translated string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file for comparison ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Helper - Override 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an upstream file and a translated file. The tool will save an .ini file that uses the translated value if it exists, otherwise it uses the value from the original file. You can convert this .ini file back to a .csf file using the &quot;Format Converter&quot; tab. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationOverrideTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationOverrideTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a translated string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file for comparison ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationTileButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Helper - Tile 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationTileTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an upstream file and a translated file, then save a new .ini file for easy comparison and checking. You can convert this .ini file back to a .csf file using the &quot;Format Converter&quot; tab. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationTileTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationTileTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an old-version upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a new-version upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an old-version translated string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file for updating the translation ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an old-version upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a new-version upstream string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load an old-version translated string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton3 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load a new-version translated string table file (.csf/.ini/.yaml/.json) ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton4 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as an .ini file for updating the translation ... 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckButton5 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Helper - Update Check 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the old upstream file, the new upstream file, the old translated file, and the new translated file. The tool will save a new .ini file that checks if any labels still have the old translation. You can convert this .ini file back to a .csf file using the &quot;Format Converter&quot; tab. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateCheckTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateCheckTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Helper - Update 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an old upstream file, a new upstream file, and your old translated file. The tool will save a new .ini file that is optimized for updating your translation. You can convert this .ini file back to a .csf file using the &quot;Format Converter&quot; tab. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_TranslationUpdateTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_TranslationUpdateTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and Apply 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_WatchModeButton1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Watch Mode 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_WatchModeTabHeader {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the text box below, enter pairs of .ini (.ini/.yaml/.json) files to monitor and the corresponding .csf files to generate. Separate each pair with a comma, and use a new line for each pair. Once started, the program will monitor the .ini (.ini/.yaml/.json) files and automatically generate the corresponding .csf file whenever a change is detected. 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_WatchModeTextBlock1 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: C:\path\to\stringtables\ra2.ini, D:\path\to\game\ra2.csf 的本地化字符串。
        /// </summary>
        public static string Xaml_Txt_WatchModeTextBlock2 {
            get {
                return ResourceManager.GetString("Xaml_Txt_WatchModeTextBlock2", resourceCulture);
            }
        }
    }
}
